from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import BigInteger, CheckConstraint, DateTime, Enum as SAEnum, ForeignKey, Index, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import AuditMixin, Base, SoftDeleteMixin


class EntryKind(str, enum.Enum):
    in_ = "in"
    out = "out"


class EntryCategory(str, enum.Enum):
    milk_sale = "milk_sale"
    fodder = "fodder"
    vet = "vet"
    emi = "emi"
    other = "other"


class EntrySource(str, enum.Enum):
    manual = "manual"
    voice = "voice"


kind_enum = SAEnum(EntryKind, name="entry_kind_enum", values_callable=lambda e: [m.value for m in e], native_enum=True, create_type=True)
category_enum = SAEnum(EntryCategory, name="entry_category_enum", values_callable=lambda e: [m.value for m in e], native_enum=True, create_type=True)
source_enum = SAEnum(EntrySource, name="entry_source_enum", values_callable=lambda e: [m.value for m in e], native_enum=True, create_type=True)


class LedgerEntry(Base, AuditMixin, SoftDeleteMixin):
    __tablename__ = "ledger_entries"

    business_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("businesses.id", ondelete="CASCADE"), nullable=False, index=True
    )
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    kind: Mapped[EntryKind] = mapped_column(kind_enum, nullable=False)
    amount_inr: Mapped[int] = mapped_column(BigInteger, nullable=False)
    category: Mapped[EntryCategory] = mapped_column(category_enum, nullable=False)
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    source: Mapped[EntrySource] = mapped_column(
        source_enum, nullable=False, default=EntrySource.manual, server_default=EntrySource.manual.value
    )

    # Idempotency key generated by the Flutter client offline. The ONLY UUID in
    # the schema — server PKs stay BIGINT.
    client_entry_id: Mapped[uuid.UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)
    synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        CheckConstraint("amount_inr > 0", name="ck_ledger_amount_positive"),
        UniqueConstraint("business_id", "client_entry_id", name="uq_ledger_business_client_entry"),
        Index("ix_ledger_business_recorded", "business_id", "recorded_at"),
    )
